//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solti.Utils.SQL.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solti.Utils.SQL.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The view cannot be determined obviously from the input sequence..
        /// </summary>
        internal static string AMBIGUOUS_RESULT {
            get {
                return ResourceManager.GetString("AMBIGUOUS_RESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base data table cannot be determined..
        /// </summary>
        internal static string BASE_CANNOT_BE_DETERMINED {
            get {
                return ResourceManager.GetString("BASE_CANNOT_BE_DETERMINED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property type should be a value type..
        /// </summary>
        internal static string CANT_SELECT {
            get {
                return ResourceManager.GetString("CANT_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property type should be a data table or view..
        /// </summary>
        internal static string CANT_WRAP {
            get {
                return ResourceManager.GetString("CANT_WRAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The list type is not compatible..
        /// </summary>
        internal static string INCOMPATIBLE_LIST {
            get {
                return ResourceManager.GetString("INCOMPATIBLE_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapping not supported..
        /// </summary>
        internal static string MAPPING_NOT_SUPPORTED {
            get {
                return ResourceManager.GetString("MAPPING_NOT_SUPPORTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one property can be annotated as &quot;empty list marker&quot;..
        /// </summary>
        internal static string MULTIPLE_EMPTY_LIST_MARKER {
            get {
                return ResourceManager.GetString("MULTIPLE_EMPTY_LIST_MARKER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No column selected.
        /// </summary>
        internal static string NO_COLUMN {
            get {
                return ResourceManager.GetString("NO_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary key can not be found on the ORM type..
        /// </summary>
        internal static string NO_PRIMARY_KEY {
            get {
                return ResourceManager.GetString("NO_PRIMARY_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortest path could not be determined..
        /// </summary>
        internal static string NO_SHORTEST_PATH {
            get {
                return ResourceManager.GetString("NO_SHORTEST_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only List&lt;&gt;&apos;s are supported..
        /// </summary>
        internal static string NOT_A_LIST {
            get {
                return ResourceManager.GetString("NOT_A_LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The expression should be a property read operation..
        /// </summary>
        internal static string NOT_A_PROPERTY {
            get {
                return ResourceManager.GetString("NOT_A_PROPERTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create temporary type from views having same named properties..
        /// </summary>
        internal static string PROPERTY_NAME_COLLISSION {
            get {
                return ResourceManager.GetString("PROPERTY_NAME_COLLISSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The SmartSqlBuilder is uninitialized. You should call the Initialize() method..
        /// </summary>
        internal static string UNINITIALIZED_BUILDER {
            get {
                return ResourceManager.GetString("UNINITIALIZED_BUILDER", resourceCulture);
            }
        }
    }
}
